### PR TITLE
add inline style attributes support

### PR DESCRIPTION
**Pull request by CobraStas**
converting 'style="attribute-name: value; ... "' into 'style={{attributeName:"value", ... }}'

### CODE REVIEW

**Comment by e-jigsaw** [comment]
@OrionStas Why we support this feature? Let me tell some example. Thanks

**Comment by CobraStas** [comment]
Pug generates standard html style attribute. When react tries render such attribute it causes error "The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX."

**Comment by e-jigsaw** [comment]
`div(style="{{marginRight: spacing + 'em'}}")` compiles to `React.createElement("div", {style: {marginRight: spacing + 'em'}})`

Need more?

**Comment by CobraStas** [comment]
This plugin called "transform-pug-to-react", so I expect, what it will transform valid pug to valid react. Right now it's not true. 
My situation: I have valid pug, what works good and I want use it in my react components. So why I should rewrite my code?

**Comment by e-jigsaw** [comment]
IMO, It can not be totally identical to Pug perfectly because this plugin has disposition of output for JSX.

* I wrote in README https://github.com/e-jigsaw/babel-plugin-transform-pug-to-react/blob/master/README.md#difference-from-pug .
* This plugin is not officially support of pug, babel, JSX.
* I want to minimize cost of maintenance.
* Small logic is effective for minimize cost of maintenance.
* This PR change is can not support when found bug or dependence package changes, and so on.

If you still does not want rewrite your code, fork and publish it please.

Thanks

**Pull request closed without merging**
